// <auto-generated />
namespace Prikhodko.NewsWebsite.Data.EntityFramework.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class EntitiesDatabaseSetup : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EntitiesDatabaseSetup));
        
        string IMigrationMetadata.Id
        {
            get { return "201904291814045_EntitiesDatabaseSetup"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
